# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dev-tae-eu-w-tes-cms-win

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present

      - name: Clean up for deployment
        run: |
          echo "Preparing deployment package..."
          echo "Files before cleanup:"
          dir

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist/
            server.js
            package.json
            package-lock.json
            web.config
            iisnode.yml
            !node_modules/
            !src/
            !public/
            !.git/
            !.github/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3A1D34CAF5A142ADA5AD26EBFBDD5BEA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8EDEDF60640840598FE853743BC967B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A437AEBF61F47F082B4B3DA9F08ADD8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'dev-tae-eu-w-tes-cms-win'
          slot-name: 'Production'
          package: .
        continue-on-error: true

      - name: 'Retry Deploy on 409 Conflict'
        if: steps.deploy-to-webapp.outcome == 'failure'
        run: |
          echo "🔄 First deployment failed, waiting before retry..."
          sleep 30
          echo "🚀 Retrying deployment..."

      - name: 'Deploy to Azure Web App (Retry)'
        if: steps.deploy-to-webapp.outcome == 'failure'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dev-tae-eu-w-tes-cms-win'
          slot-name: 'Production'
          package: .
